pick: random

# TODO test with different JDKs

configs:
  windows-jdk11:
    os: windows
    jdk: 11
  windows-jdk15:
    os: windows
    jdk: 15
  linux-jdk11:
    os: linux
    jdk: 11
  linux-jdk15:
    os: linux
    jdk: 15
  macos-jdk11:
    os: macos
    jdk: 11
  macos-jdk15:
    os: macos
    jdk: 15

defaults:
  isabelle: return "2019"
  isabellehome: |
    if os=="macos": return f"~/install/Isabelle{get('isabelle')}.app/Isabelle"
    return f"~/install/Isabelle{get('isabelle')}"
  machine_config: |
    if os=="windows": return "executor: { name: windows/default }"
    if os=="linux": return "machine: {image: ubuntu-2004:202010-01}"
    if os=="macos": return "macos: {xcode: 11.6.0}"
  sha1sum: |
    if os=="macos": return "shasum"
    return "sha1sum"
  win_or_unix: |
    if os=="windows": return "windows"
    return "unix"
  jdkversionprefix: |
    if jdk=="8": return "1.8"
    if int(jdk)>=11: return str(int(jdk))
